# Generated by Django 4.0.2 on 2022-04-22 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='staffdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staffid', models.IntegerField()),
                ('staffname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='leaveapplied',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staffid', models.IntegerField()),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('noofdays', models.IntegerField()),
                ('leavebalance', models.IntegerField()),
                ('staffname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staffleave.staffdetails')),
            ],
        ),
    ]
