# Generated by Django 4.0.2 on 2022-04-24 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staffleave', '0002_remove_leaveapplied_staffname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplied',
            name='leavebalance',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='leaveapplied',
            name='noofdays',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='leaveapplied',
            name='staffid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel', to='staffleave.staffdetails'),
        ),
    ]
