# Generated by Django 4.0.2 on 2022-04-24 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staffleave', '0003_alter_leaveapplied_leavebalance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplied',
            name='staffid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staffleave.staffdetails'),
        ),
    ]
