# Generated by Django 4.0.2 on 2022-04-24 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staffleave', '0004_alter_leaveapplied_staffid'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffdetails',
            name='staffdept',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='leaveapplied',
            name='staffid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel', to='staffleave.staffdetails'),
        ),
    ]
